-- Logando no serviço MariaDB 
MariaDb -u root -p

-- DML --

-- Listar todos os Bancos
SHOW DATABASES;

-- Criar um novo banco de dados
CREATE DATABASE ESCOLA;

-- Acessar o banco de dados ESCOLA;
USE ESCOLA;
    ex: MariaDb[none]>
    ex: MariaDb[ESCOLA]> 

--  Criar uma nova tabela
CREATE TABLE ALUNOS(
    NOME VARCHAR(255),
    TELEFONE VARCHAR(16)
);  

CREATE TABLE PROFESSORES(
    NOME VARCHAR(255),
    EMAIL VARCHAR(255),
    SALARIO DECIMAL(9,2)
);

-- Lista todas as tabelas
SHOW TABLES;

DESC ALUNOS;
DESC PROFESSORES;

 -- SQL -- 
 
 -- INSERT
 -- DELETE
 -- UPDATE
 -- SELECT

-- INSERT
INSERT INTO ALUNOS(NOME, TELEFONE) VALUES("FELIPE", "46997327327327");
INSERT INTO ALUNOS(NOME, TELEFONE) VALUES("JOSÉ", "469121297913");
INSERT INTO ALUNOS(NOME, TELEFONE) VALUES("MARIA", "469S123232323");

INSERT INTO PROFESSORES(NOME, EMAIL, SALARIO) VALUES("GUILHERME", "guilherme@gmail.com", 350.75);
INSERT INTO PROFESSORES(NOME, EMAIL, SALARIO) VALUES("KEVIN", "kevin@gmail.com", 10000.45);

-- SELECT 
SELECT * FROM ALUNOS;
SELECT * FROM PROFESSORES;

-- SELECT COMW WHERE
/*
<
>
<=
>=
<> */

SELECT * FROM PROFESSORES WHERE NOME = "GUILHERME";

-- UPDATE

UPDATE PROFESSORES SET SALARIO = 625.43 WHERE NOME = "GUILHERME";
UPDATE PROFESSORES SET NOME = "GUILHERME PIRES" WHERE NOME = "GUILHERME";
UPDATE PROFESSORES SET EMAIL = "NOVO_EMAIL@GMAIL.COM" WHERE NOME = "GUILHERME PIRES";

UPDATE ALUNOS SET RA = "123" WHERE NOME = "FELIPE";
UPDATE ALUNOS SET RA = "124" WHERE NOME = "JOSÉ";
UPDATE ALUNOS SET RA = "125" WHERE NOME = "MARIA";

--DELETE 
DELETE FROM PROFESSORES WHERE NOME = "KEVIN";


-- Alterando a estrutura de uma tabela
-- Adiciona um novo campo em uma tabela
ALTER TABLE ALUNOS ADD COLUMN RA VARCHAR(5);

-- Apaga um campo de uma tabela 
ALTER TABLE ALUNOS DROP COLUMN RA;

-- Modificando um campo de uma tabela
ALTER TABLE ALUNOS MODIFY COLUMN RA INT(2);

ALTER TABLE PROFESSORES ADD COLUMN DISCIPLINA VARCHAR(255);

-- Renomear nome do campo
ALTER TABLE PROFESSORES RENAME COLUMN DISCIPLINA TO DISCIPLINA2;

-- Renomear nome da tabela
RENAME TABLE PROFESSORES2 TO PROFESSORES2;


CREATE TABLE ALUNOS(
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(16) 
);

INSERT INTO ALUNOS(NOME, TELEFONE) VALUES("FELIPE", "46997327327327");
INSERT INTO ALUNOS(NOME) VALUES("");

ALTER TABLE ALUNOS MODIFY TELEFONE VARCHAR(16) NOT NULL;

UPDATE ALUNOS SET TELEFONE = "";