CREATE DATABASE ESCOLA;

USE ESCOLA;

CREATE TABLE ALUNOS(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL
);

INSERT INTO ALUNOS(ID, NOME) VALUES(null,"Guilherme");
INSERT INTO ALUNOS(ID, NOME) VALUES(null,"Jose");
INSERT INTO ALUNOS(NOME) VALUES("Maria");

INSERT INTO ALUNOS(ID, NOME) VALUES(75, "Lucas");
INSERT INTO ALUNOS( NOME) VALUES("Jordana");
INSERT INTO ALUNOS(ID, NOME) VALUES(4, "Bruno");

UPDATE ALUNOS SET NOME = "Leonardo" WHERE ID = 2;


ALTER TABLE ALUNOS ADD COLUMN ATIVO BOOLEAN NOT NULl DEFAULT(TRUE);

INSERT INTO ALUNOS(NOME, ATIVO) VALUES("VALENTINA", FALSE);
INSERT INTO ALUNOS(NOME) VALUES("Pamela");

ALTER TABLE ALUNOS ADD COLUMN RA VARCHAR(100) NOT NULL DEFAULT("SEM REGISTRO");

UPDATE ALUNOS SET  RA = "123" WHERE id = 1;
UPDATE ALUNOS SET  RA = "124" WHERE id = 2;
UPDATE ALUNOS SET  RA = "125" WHERE id = 3;
UPDATE ALUNOS SET  RA = "126" WHERE id = 4;
UPDATE ALUNOS SET  RA = "127" WHERE id = 75;
UPDATE ALUNOS SET  RA = "128" WHERE id = 76;
UPDATE ALUNOS SET  RA = "129" WHERE id = 77;
UPDATE ALUNOS SET  RA = "130" WHERE id = 78;

INSERT ALUNOS(NOME) VALUES("Loreni");
INSERT ALUNOS(NOME, RA) VALUES("Edson", "131");


SELECT * FROM ALUNOS ORDER BY NOME DESC;

-- Busca palavras proximas no inicio da do campo
SELECT * FROM ALUNOS WHERE NOME like "G%";

-- Busca palavras proximas no final da do campo
SELECT * FROM ALUNOS WHERE NOME like "%G";

-- Busca palavras proximas
SELECT * FROM ALUNOS WHERE NOME like "%G%";
--AND &&
--OR ||
--NOT !==

SELECT * FROM ALUNOS WHERE NOME LIKE "B%" AND ATIVO = 1;
SELECT * FROM ALUNOS WHERE NOME LIKE "G%" OR NOME LIKE "L%";
SELECT * FROM ALUNOS WHERE NOT NOME LIKE "%U%";

ALTER TABLE ALUNOS ADD COLUMN DATA_NSC DATE;


INSERT INTO ALUNOS(NOME,DATA_NSC) VALUES("Gabriel", "2001-03-25");

UPDATE alunos
SET DATA_NSC = CASE ID
    WHEN 1 THEN '1995-05-10'
    WHEN 2 THEN '1988-09-22'
    WHEN 3 THEN '2000-01-15'
    WHEN 4 THEN '1992-07-30'
    WHEN 75 THEN '1999-12-05'
    WHEN 76 THEN '2001-04-18'
    WHEN 77 THEN '1997-11-11'
    WHEN 78 THEN '1990-06-25'
    WHEN 80 THEN '1985-02-14'
END
WHERE ID IN (1, 2, 3, 4, 75, 76, 77, 78, 80);

SELECT * FROM ALUNOS 
WHERE DATA_NSC IS NOT NULL 
ORDER BY DATA_NSC ASC
LIMIT 1;