CREATE DATABASE ESCOLA;

use ESCOLA;

CREATE TABLE ALUNO(
    RA VARCHAR(6) NOT NULL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    NASCIMENTO DATE NOT NULL
);

CREATE TABLE CURSO(
    CODIGO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CH INT NOT NULL,
    INICIO DATE NOT NULL,
    TERMINO DATE NOT NULL
);

CREATE TABLE MATRICULA(
    CURSO INT NOT NULL,
    RA VARCHAR(6) NOT NULL,
    DATA DATE NOT NULL,
    VALOR DECIMAL(9, 2) NOT NULL,
    FOREIGN KEY (CURSO) REFERENCES CURSO(CODIGO),
    FOREIGN KEY (RA) REFERENCES ALUNO(RA)
);